### Get all todos
GET http://localhost:8080/api/todos
### Get existing todo by id

GET http://localhost:8080/api/todos/1
### Get non-existing todo by id 
GET http://localhost:8080/api/todos/999
### Create new todo
POST http://localhost:8080/api/todos  
Content-Type: application/json

{
  "title": "New Todo",
  "priority": "High"
}
### Create new todo with title that already exists
POST http://localhost:8080/api/todos
Content-Type: application/json

{
  "title": "Buy groceries",
  "priority": "High"
}

### Delete existing todo
DELETE http://localhost:8080/api/todos/1
### Delete non-existing todo
DELETE http://localhost:8080/api/todos/999
###

